# This is a workflow to deploy master branch

name: Deploy_on_site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64

    - name: pip update
      run: |
        python -m pip install --upgrade pip

    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Initialize Repository
      run: |
        pip install -r requirements.txt
        sh tools/init.sh

    - name: Make the Product
      run: |
        rm -rf previews
        mkdir -p output/previews
        mv output/previews ./
        make clean && make publish || true
        mv ./previews output/

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.bot_identity }}
        name: identity
        known_hosts: ${{ secrets.known_hosts }}
        config: |
          Host github
            HostName github.com
            User git
            IdentityFile ~/.ssh/identity

    - name: Check Update
      id: check_update
      run: |
        git fetch origin master
        cur_hash=`git rev-parse master`
        new_hash=`git rev-parse origin/master`
        if [ $cur_hash=$new_hash ]; then
          newest='true'
        else
          newest='false'
        fi
        echo "::set-output name=NEWEST::$newest"

    - name: Deploy on Site
      if: steps.check_update.outputs.NEWEST=='true'
      run: |
        cd output/
        git config user.name $GITHUB_ACTOR
        git config --add url.github:.pushInsteadOf https://github.com/
        git config --add url.github:.pushInsteadOf git@github.com:
        git add .
        git commit -m 'master branch updated.' && git push -f || true
