# This is a workflow to preview branches

name: Preview

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches-ignore:
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_preview:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64

    - name: pip update
      run: |
        python -m pip install --upgrade pip

    - name: Checkout branch
      uses: actions/checkout@v2
      # checkout the branch which trigerred this workflow.
      with:
        submodules: true

    - name: Make the Product
      run: |
        pip install -r requirements.txt
        sh tools/init_repository.sh
        {
          echo
          echo "SITEURL = '/previews/$GITHUB_REF'"
          echo "if 'PREVIEW_SITENAME_APPEND' in globals():"
          echo "    SITENAME += PREVIEW_SITENAME_APPEND"
          echo "    SITETAG += PREVIEW_SITENAME_APPEND"
        } >> ./content/contentconf.py
        make html
        git rev-parse HEAD > ./git_head_hash

    - name: Save Preview Product
      uses: actions/upload-artifact@v1
      with:
        name: preview
        path: output

  push_to_site:
    # The type of runner that the job will run on
    needs: build_preview
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64

    - name: Load Preview Product
      uses: actions/download-artifact@v1
      with:
        name: preview

    - name: Get preview hash
      id: get_preview_hash
      run: |
        hash_file="./preview/git_head_hash"
        cur_hash=${<$hash_file}
        rm hash_file
        echo "::set-output name=cur_hash::$cur_hash"
 
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master
        submodules: false

    - name: Initialize Output Repository
      run: |
        sh tools/init_output.sh

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.bot_identity }}
        name: identity
        known_hosts: ${{ secrets.known_hosts }}
        config: |
          Host github
            HostName github.com
            User git
            IdentityFile ~/.ssh/identity

    - name: Check update of original branch
      id: check_update
      env:
        cur_hash: ${{ steps.get_preview_hash.outputs.cur_hash }}
      run: |
        branch=${GITHUB_REF#refs/heads/}
        git fetch origin "$branch"
        new_hash=`git rev-parse --verify --quiet "origin/$branch"`
        if [ $cur_hash=$new_hash ]; then
          newest='true'
        else
          newest='false'
        fi
        echo "::set-output name=newest::$newest"

    - name: Set Preview in the output directory
      if: steps.check_update.outputs.newest=='true'
      run: |
        cd ./output
        git pull
        mkdir -p ./previews/$GITHUB_REF
        rm -rf ./previews/$GITHUB_REF
        mv ../preview ./previews/$GITHUB_REF

    - name: Deploy on Site
      if: steps.check_update.outputs.newest=='true'
      run: |
        cd output/
        git config user.name $GITHUB_ACTOR
        git config --add url.github:.pushInsteadOf https://github.com/
        git config --add url.github:.pushInsteadOf git@github.com:
        git add .
        git commit -m "${GITHUB_REF#refs/heads/} branch updated." && git push || true
